name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: |
          Hello @${{ github.actor }}!

          Thank you for opening a pull request. We appreciate your contribution.

          Please make sure to follow our contribution guidelines and address any feedback that we provide.

          Thanks again!
